fix min and max browser version from int to string
LykkeCity/Lykke.Backoffice.Common pull request #2
Opened 2018-07-06 12:43 UTC by olegtrofimenko

2018-07-06 12:45 UTC, mskobzev-old approved these changes

2018-07-06 12:48 UTC, mskobzev-old requested changes

2018-07-06 12:48 UTC, simpllfy commented on tests/Lykke.Backoffice.Common.Tests/CheckBrowserTest.cs
> +                MinMajorVersion = "25"
Add tests on max version as well

2018-07-09 07:15 UTC, mskobzev-old approved these changes

2018-07-09 10:17 UTC, ozhelenkov approved these changes

2018-07-09 10:42 UTC, merged